apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: redpanda-console
  namespace: redpanda
spec:
  dependsOn:
    - name: redpanda
      namespace: redpanda
  interval: 5m
  chart:
    spec:
      chart: console
      version: "3.*"
      sourceRef:
        kind: HelmRepository
        name: redpanda
        namespace: redpanda
      interval: 1m
  values:
    console:
      config:
        kafka:
          brokers:
            - redpanda.redpanda.svc.cluster.local:9093
    service:
      type: ClusterIP
      port: 8080
