apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: redpanda-connect
  namespace: redpanda-connect
spec:
  interval: 5m
  chart:
    spec:
      chart: connect
      version: "3.*"
      sourceRef:
        kind: HelmRepository
        name: redpanda
        namespace: redpanda
      interval: 1m
  values:
    config:
      input:
        generate:
          mapping: |
            root.message = "Hello, Redpanda Connect!"
          count: 0
      pipeline:
        processors:
          - mapping: |
              root.message = this.message.uppercase()
      output:
        stdout: {}
