apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: redpanda-connect
  namespace: demo
  labels:
    app: redpanda-connect
spec:
  selector:
    matchLabels:
      app: redpanda-connect
  endpoints:
    - port: http
      path: /metrics
      interval: 30s
