apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: apps
  namespace: flux-system
spec:
  interval: 5m
  timeout: 5m
  retryInterval: 1m
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./apps

  # Apps depend on infrastructure being ready
  dependsOn:
    - name: infrastructure

  # Health checks for application components
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: minio
      namespace: demo
    - apiVersion: apps/v1
      kind: Deployment
      name: upload-ui
      namespace: demo
    - apiVersion: apps/v1
      kind: Deployment
      name: mock-api
      namespace: demo
    - apiVersion: apps/v1
      kind: Deployment
      name: redpanda-connect
      namespace: demo
