apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio-data
  namespace: demo
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: standard
