---
# NodePort service for Redpanda Console access
apiVersion: v1
kind: Service
metadata:
  name: redpanda-nodeport
  namespace: redpanda
  labels:
    app.kubernetes.io/name: redpanda
spec:
  type: NodePort
  ports:
    - name: kafka
      port: 9093
      targetPort: 9093
      nodePort: 30092
      protocol: TCP
    - name: schema-registry
      port: 8081
      targetPort: 8081
      nodePort: 30081
      protocol: TCP
    - name: admin
      port: 9644
      targetPort: 9644
      nodePort: 30644
      protocol: TCP
  selector:
    app.kubernetes.io/name: redpanda
    app.kubernetes.io/component: redpanda
