apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: redpanda
  namespace: redpanda
spec:
  interval: 5m
  timeout: 15m
  chart:
    spec:
      chart: redpanda
      version: "5.9.x"
      sourceRef:
        kind: HelmRepository
        name: redpanda
        namespace: flux-system
      interval: 1m
  dependsOn:
    - name: cert-manager
      namespace: cert-manager
  values:
    # Core cluster configuration
    statefulset:
      initContainers:
        setDataDirOwnership:
          enabled: true

    # Enable metrics for monitoring
    monitoring:
      enabled: true
      scrapeInterval: 30s

    # Console access
    console:
      enabled: false  # Deployed separately for GitOps demo
