apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: redpanda
  namespace: redpanda
spec:
  interval: 5m
  timeout: 10m
  chart:
    spec:
      chart: redpanda
      version: "5.9.x"
      sourceRef:
        kind: HelmRepository
        name: redpanda
        namespace: flux-system
      interval: 1m
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  dependsOn:
    - name: cert-manager
      namespace: cert-manager
  values:
    # Core cluster configuration
    statefulset:
      replicas: 3

    # Resource allocation for kind cluster
    resources:
      cpu:
        cores: 1
      memory:
        # Ensure we meet minimum requirements
        container:
          min: 2Gi
          max: 2Gi
        # Bypass memory check for development
        redpanda:
          memory: 2Gi
          reserveMemory: 1Gi

    # Storage for local development
    storage:
      persistentVolume:
        enabled: true
        size: 10Gi
        storageClass: standard

    # Affinity to distribute brokers across workers
    affinity:
      podAntiAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchLabels:
                app.kubernetes.io/name: redpanda
            topologyKey: kubernetes.io/hostname

    # External access configuration for kind cluster
    external:
      enabled: false  # Disable external access for simplicity

    # Listeners configuration
    listeners:
      kafka:
        port: 9093  # Internal port

      schemaRegistry:
        enabled: true
        port: 8081

      admin:
        port: 9644

      http:
        enabled: true
        port: 8082

    # Enable metrics for monitoring
    monitoring:
      enabled: true
      scrapeInterval: 30s

    # Console access
    console:
      enabled: false  # Deployed separately for GitOps demo

    # Tuning for local development
    tuning:
      tune_aio_events: false
      tune_clocksource: false
      tune_coredump: false

    # Developer mode - bypass resource checks
    config:
      cluster:
        developer_mode: true
